version: '3'

services:
  masky:
    build:
      context: ./masky/
      args:
        APT_MIRROR: ftp.tw.debian.org
    container_name: masky
    working_dir: /opt/pluvio/challenge/
    env_file: .env
    ports:
      - "8080:80"
    networks:
      - masky_network
    depends_on:
      - "mongodb"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "8027:27017"
    networks:
      - masky_network

networks:
  masky_network:
    driver: bridge
